server:
  port: 8106

spring:
  application:
    name: springCloud-consumer-feign-cust


eureka: 
  client: 
    service-url: 
      defaultZore: http://user:password@localhost:8761/eureka
      
      
logging:
  level:
    com.jja.UserFeignClient: DEBUG