spring:
  application:
    name: mc-turbine
server:
  port: 9999

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: turbine-service
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 127.0.0.1
turbine:
  aggregator:
    cluster-config: default
  app-config: user-service,orderItem-service,order-service
  cluster-name-expression: new String("default")

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
  endpoint:
    health:
      show-details: always