server:
  port: 10000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: header_route
        uri: http://baidu.com
        predicates:
        - Header=X-Request-Id, \d+
        - Path=/spring-cloud

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    appname: MICRO-SERVICE-GATEWAY
    status-page-url-path: /health
