spring: 
  application:
    name: springCloud-provider-ribbon-withoutEu
    
server:
  port: 8104

eureka:
  client: 
    serviceUrl:
      defaultZone: http://user:password123@localhost:8761/eureka

#脱离eureka使用
ribbon:
  eureka:
   enabled: false
   
springCloud-provider:
  ribbon:
    listOfServers: localhost:8001
    
    