server:
  port: 9002

spring:
  application:
    name: mc-order

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: order-service
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator