spring: 
  application:
    name: mc-ribbon
    
server:
  port: 8102
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: service-ribbon

# 脱离eureka使用
ribbon:
  eureka:
    enabled: false


# 配置负载均衡的规则
mc-user:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    # 脱离eureka使用
    listOfService: http://localhost:9001,http://localhost:9002
    # 请求连接的超时时间。
    ConnectTimeout: 1000
    # 请求处理的超时时间
    ReadTimeout: 1000
    # 对所以操作请求都进行重试
    OkToRetryOnAllOperations: true

