server:
  port: 9003

spring:
  application:
    name: mc-orderItem

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: orderItem-service
    # 此实例注册到eureka服务端的唯一的实例ID,其组成为${spring.application.name}:${spring.application.instance_id}:${random.value}
    instance-id: ${spring.application.name}:${server.port}
    # 获取实例的ip地址
    ip-address: 127.0.0.1

management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor