server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    #  instance:
    #    ip-address: localhost
    #    instance-id: ${spring.application.name}:${server.port}
    registry-fetch-interval-seconds: 10
  instance:
    metadata-map:       #自定义元数据
      zone: ABC
      ruolin: BBC
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    appname: USER-SERVICE
    hostname: localhost
    status-page-url-path: /health
    namespace: eureka

spring:
  application:
    name: user
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 20MB


# spring boot 2.x actuator 的配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  endpoint:
    health:
      show-details: always
