server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://39.108.125.41:8761/eureka
#      instance:
        # 获取实例的ip地址
#        ip-address: 127.0.0.1
        # 此实例注册到eureka服务端的唯一的实例ID,其组成为${spring.application.name}:${spring.application.instance_id:${random.value}}
#        instance-id: ${spring.application.name}:${server.port}
    registry-fetch-interval-seconds: 10
  instance:
    # 自定义元数据
    metadata-map:
      zone: ABC
      test: BBC
    lease-renewal-interval-in-seconds: 5
    prefer-ip-address: true
    appname: user-service
    hostname: localhost
    status-page-url-path: /health
    namespace: eureka

spring:
  application:
    name: mc-user
  servlet:
    multipart:
      max-file-size: 120MB
      max-request-size: 20MB

# spring boot 2.x actuator 的配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /monitor
  endpoint:
    health:
      show-details: always

swagger:
  show: true