server:
  port: 8105
spring:
  application:
    name: mc-feign

eureka:
  client: 
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: service-feign
    instance-id: ${spring.application.name}:${server.port}

ribbon:
  eager-load:
    enabled: false