spring:
  application:
    # 本服务注册到注册到服务器的名称, 这个名称就是后面调用服务时的服务标识符
    name: cloud-dashboard-zipkin
  zipkin:
    enabled: true
    # zipkkin dashboard的地址：通过真实IP地址访问
    baseUrl: http://localhost:17601/
    # 通过cloud-dashboard-zipkin注册到注册中心的服务名称访问，本版本(spring-cloud-sleuth-core-1.2.5.RELEASE)不支持，需要从spring-cloud-sleuth-core-1.3.0.RELEASE开始支持这个功能
    # 配置如下：
    # baseUrl: http://cloud-dashboard-zipkin/
  sleuth:
    sampler:
      #  默认值为0.1f，现在为了测试设置100%采集
      percentage: 1

eureka:
  client:
    serviceUrl:
      # 服务器注册/获取服务器的zone
      defaultZone: http://127.0.0.1:10761/eureka/
      # defaultZone: http://192.168.21.3:10761/eureka/,http://192.168.21.4:10761/eureka/
  instance:
    prefer-ip-address: true
