eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: spring-cloud-bus
  rabbitmq:
    host: localhost
    port: 9021
    username: cloud
    password: xxxx

