server:
  port: 9100

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: service-config
    instance-id: ${spring.application.name}:${server.port}

#自定义默认属性
#name: defaultName
#profile: defaultProfile
#level: defaultLevel