server:
  port: 9100

# 自定义默认属性
# name: defaultName
# profile: defaultProfile
# level: defaultLevel

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: cloud
    password: cloud
    virtual-host: /mc
    publisher-confirms: true
