server:
  port: 8110

spring:
  application:
    name: springCloud-consumer-feign-hystrix-wo-hystrix


eureka: 
  client: 
    service-url: 
      defaultZore: http://user:password@localhost:8761/eureka
      
