server:
  port: 9000

spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/thethink/config_repo      # 公用
          repos:
            simple: https://gitee.com/thethink/simple
            special:
              pattern: special*/dev*,special*/test*
              uri: https://gitee.com/thethink/special
