spring: 
  application:
    name: springCloud-provider-ribbon-hystrix
    
server:
  port: 8108

eureka:
  client: 
    service-url:
      defaultZore: http://user:password123@localhost:8761/eureka
      
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
