server:
  port: 10000

spring:
  application:
    name: mc-zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: zuul-service
    instance-id: ${spring.application.name}:${server.port}
    ip-address: 127.0.0.1

zuul:
   ignored-patterns:
   - /**/page/**
   # 访问 zuul 的前缀
   prefix: /api
   # 去掉前缀为 false 默认 true
   strip-prefix: true
   # 忽略那些服务
   ignored-services: mc-user
   routes:
     user:
       path: /api-user/**
       url: http://127.0.0.1:9001
       sensitiveHeaders: Cookie,Set-Cookie,Authorization
     mc-order:
       path: /api-order/**
       serviceId: mc-order
     goods:
       path: /api-goods/**
       serviceId: mc-goods


ribbon:
  eureka:
    enabled: true

#mc-user:
#  ribbon:
#    listOfServers: http://localhost:9001