server:
  port: 8080
spring:
  application:
      name: mc-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/janlle/config_repo.git
          # git配置文件保存的位置（启动时会拉取远程的配置）
          basedir: D:\tmp\config
          # 访问git仓库的用户名（非私有库可以不用配置）
          # username: janlle
          # 访问git仓库的密码（非私有库可以不用配置）
          # password: admin
          # uri: ${user.dir}\spring-cloud-config-server\src\main\resources\configs
          search-paths: /
          # 在启动的时候就会下载
          clone-on-start: true
      # git 分支
      label: master
  rabbitmq:
    host: localhost
    port: 5672
    username: cloud
    password: xxxx
    virtual-host: /mc

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    appname: service-config-server
    instance-id: ${spring.application.name}:${server.port}

# spring boot 2.x actuator 的配置
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
    health:
      showDetails: always


