spring:
  application:
    name: springCloud-gateway-zuul

server:
  port: 8111
  
eureka: 
  client: 
    service-url: 
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

