spring:
  application:
    name: springCloud-gateway-zuul

server:
  port: 8111
  
eureka: 
  client: 
    service-url: 
      defaultZone: http://user:password123@localhost:8761/eureka
  instance:
    prefer-ip-address: true

#脱离eureka使用zull
ribbon:
  eureka:
    enabled: false

zuul:
  routes:
    abc:
      path: /user-url/**
      serviceId: springcloud-provider


springcloud-provider:
  ribbon:
    listOfService: http://localhost:8001,http://localhost:8002